routes/web.php
            ->name('editCarTypeStatus');

        Route::resource('/rushhours', 'Admin\RushhourController');
        Route::post('/rushhours/edit', 'Admin\RushhourController@edit_rushhour')->name('editRushhour');
        Route::get('/rushhours/delet/{id}', 'Admin\RushhourController@delete_rushhour')->name('deleteRushhour');

        Route::resource('/reasons', 'Admin\ReasonController');
        Route::post('/reasons/edit', 'Admin\ReasonController@edit_reason')->name('editReason');
        Route::get('/reasons/delet/{id}', 'Admin\ReasonController@delete_reason')->name('deleteReason');

        Route::resource('/reasons', 'Admin\ReasonController');
        Route::post('/reasons/edit', 'Admin\ReasonController@edit_reason')->name('editReason');
        Route::get('/reasons/delet/{id}', 'Admin\ReasonController@delete_reason')->name('deleteReason');
//
        Route::resource('/issues', 'Admin\IssueController');
        Route::post('/issues/edit', 'Admin\IssueController@edit_issue')->name('editIssue');
        Route::get('/issues/delet/{id}', 'Admin\IssueController@delete_issue')->name('deleteIssue');
//
        Route::resource('/bank_account', 'Admin\BankAccountController');
        Route::post('/bank_account/edit', 'Admin\BankAccountController@edit_bank_account')->name('editBankAccount');
        Route::get('/bank_account/delet/{id}', 'Admin\BankAccountController@delete_bank_account')->name('deleteBankAccount');
//
        Route::resource('/losts', 'Admin\LostController');
        Route::get('/losts-text', 'Admin\LostController@lostText')->name('losts.text');

        Route::post('/losts/edit', 'Admin\LostController@edit_lost')->name('editLost');
        Route::get('/losts/delet/{id}', 'Admin\LostController@delete_lost')->name('deleteLost');
//
        Route::resource('/bank_transfers', 'Admin\BankingTransferController');
        Route::get('/bank_transfers_admin', 'Admin\BankingTransferController@from_admin')->name('bank_transfers.from_admin');
//
        Route::get('/promocodes/{department_id}', 'Admin\PromocodeController@index')->name('promocodes.index');

        Route::resource('/promocodes', 'Admin\PromocodeController', ['except' => ['index']]);
        Route::get('/promocodes/delet/{id}', 'Admin\PromocodeController@delete_promo')->name('deletePromo');

        Route::resource('/carlevelss', 'Admin\LevelController');
        Route::post('/carlevelss/edit', 'Admin\LevelController@edit_carlevels')->name('editCarlevel');
        Route::get('/carlevelss/editStatus/{id}', 'Admin\LevelController@editCarlevelStatus')
            ->name('editCarlevelStatus');

        Route::resource('/carprices', 'Admin\CarPriceController');
        Route::post('/carprices/edit', 'Admin\CarPriceController@edit_carprices')->name('editCarprice');

        Route::resource('/govs', 'Admin\GovController');
        Route::post('/govs/edit', 'Admin\GovController@edit_gov')->name('editGov');

        Route::resource('/cities', 'Admin\CityController');
        Route::post('/cities/edit', 'Admin\CityController@edit_city')->name('editCity');

        Route::resource('/cats', 'Admin\CategoryController');
        Route::post('/cats/edit', 'Admin\CategoryController@edit_cat')->name('editCat');
        Route::get('/cats/editStatus/{id}', 'Admin\CategoryController@editCatStatus')->name('editCatStatus');

        Route::resource('/periods', 'Admin\PeriodController');
        Route::post('/periods/edit', 'Admin\PeriodController@editPeriod')->name('editPeriod');
        Route::get('/periods/editStatus/{id}', 'Admin\PeriodController@editPeriodStatus')->name('editPeriodStatus');


        Route::resource('/trips', 'Admin\TripController');
        Route::get('/finished-trips', 'Admin\TripController@finishedTrips');
        Route::get('/unfinished-trips', 'Admin\TripController@unfinishedTrips');
        Route::get('/cancelled-trips', 'Admin\TripController@cancelledTrips');
        Route::post('/trips', 'Admin\TripController@checkPaymentSrtatus')->name('checkPaymentSrtatus');
//Route::get('/offs/editStatus/{id}', 'Admin\OfferController@editOfferStatus')->name('editOfferStatus');

        Route::resource('/notifications', 'Admin\NotificationController');
        Route::get('/notifications/delet/{id}', 'Admin\NotificationController@delete_not');

        Route::resource('/reviews', 'Admin\ReviewController');
        Route::get('/reviews/delet/{id}', 'Admin\ReviewController@delete_review');

        Route::resource('/terms', 'Admin\TermController');
        Route::post('/terms/edit', 'Admin\TermController@edit_terms')->name('editTerm');
        Route::get('/complains_suggestions/{type}', 'Admin\ComplainSuggestController@index')->name('complains_suggestions.index');
        Route::get('/finished-complains/{type}', 'Admin\ComplainSuggestController@finished')->name('complains_suggestions.finished.index');
        Route::get('/close-complain/{complain_id}', 'Admin\ComplainSuggestController@closeComplain')->name('complain.close');

        Route::resource('/complains_suggestions', 'Admin\ComplainSuggestController', ['except' => ['index']]);
        Route::get('/download-complains/{status}', 'Admin\ComplainSuggestController@downloadComplains')->name('complains.download');

        Route::get('/contact_us/{type}', 'Admin\ContactusController@index')->name('contact_us.index');
        Route::get('/closed-contact_us/{type}', 'Admin\ContactusController@closedContacts')->name('contact_us.closed.index');
        Route::get('/close/{contact_id}', 'Admin\ContactusController@close')->name('contact-us.close');
        Route::resource('/contact_us', 'Admin\ContactusController', ['except' => ['index']]);

        Route::resource('/abouts', 'Admin\AboutController');
        Route::post('/abouts/edit', 'Admin\AboutController@edit_abouts')->name('editAbout');
        Route::get('/settings/{department_id}', 'Admin\SettingController@index')->name('settings.index');

        Route::resource('/settings', 'Admin\SettingController', ['except' => ['index']]);
        Route::post('/settings/edit', 'Admin\SettingController@edit_settings')->name('edit_settings');
        Route::get('/app_explanations/{type}', 'Admin\AppExplanationController@index')->name('app_explanations.index');

        Route::resource('/app_explanations', 'Admin\AppExplanationController', ['except' => ['index']]);
        Route::post('/app_explanations/edit', 'Admin\AppExplanationController@edit_explains')->name('editExplain');
        Route::post('/app_explanations/delet', 'Admin\AppExplanationController@deleteAppExplanations')->name('deleteAppExplanations');

        Route::get('/app_privacies', 'Admin\AppPrivacyController@index');
        Route::post('/app_privacies', 'Admin\AppPrivacyController@createPrivacy')->name('createPrivacy');
        Route::get('/app_privacies/{id}', 'Admin\AppPrivacyController@editView')->name('editPrivacyView');
        Route::post('/app_privacies/edit', 'Admin\AppPrivacyController@edit_explains')->name('editPrivacy');
        Route::post('/app_privacies/delet', 'Admin\AppPrivacyController@deleteAppExplanations')->name('deletePrivacy');


        Route::resource('/categories', 'Admin\CategoryController');
        Route::post('/categories/mainCat', 'Admin\CategoryController@storeMainCat')->name('storeMainCat');
        Route::post('/categories/delet', 'Admin\CategoryController@delete_cat')->name('deleteCat');
        Route::get('/shops/branches/{shop_id}', 'Admin\ShopController@branches')->name('shop.branches');

        Route::resource('/shops', 'Admin\ShopController');
        Route::get('/download-shops/{active}', 'Admin\ShopController@downloadShops')->name('shops.download');
        Route::post('/shops/editStatus', 'Admin\ShopController@editShopStatus')->name('editShopStatus');
        Route::post('/shops/editVerified', 'Admin\ShopController@editShopVerified')->name('editShopVerified');
        Route::get('/shops/create', 'Admin\ShopController@createShop')->name('createShop');
        Route::get('/shops-by-area', 'Admin\ShopController@shopsByArea')->name('shopsByArea');
        Route::post('/shops-by-area', 'Admin\ShopController@shopsByAreaSearch')->name('shopsByAreaSearch');
        Route::get('/shops/edit/{shop_id}', 'Admin\ShopController@editShop')->name('editShop');
        Route::get('/shops/orders/{shop_id}', 'Admin\ShopController@orders')->name('shops.orders');
        Route::post('/shops/orders/search', 'Admin\ShopController@searchOrders')->name('shops.orders.search');
        Route::post('/shops/edit', 'Admin\ShopController@updateShop')->name('updateShop');
        Route::post('/shops/delet', 'Admin\ShopController@delete_shop')->name('deleteShop');
        Route::get('/active-shops', 'Admin\ShopController@activeShops');
        Route::get('/inactive-shops', 'Admin\ShopController@inactiveShops');
        Route::get('/shop_requests', 'Admin\ShopController@shopRequests')->name('shopRequests');
        Route::post('/shop_requests/delete', 'Admin\ShopController@destroyRequest')->name('shopRequests.delete');
        Route::get('/shop_requests/accept/{id}', 'Admin\User2Controller@acceptShop')->name('acceptShop');
        Route::post('/shop_requests/editStatus', 'Admin\ShopController@editRequestStatus')->name('editRequestStatus');


        Route::resource('/all-orders', 'Admin\OrderController');
        Route::post('/orders/search', 'Admin\OrderController@search')->name('orders.search');
        Route::get('/download-orders', 'Admin\OrderController@downloadOrders')->name('orders.download');
        Route::post('/orders/search-status', 'Admin\OrderController@searchStatus')->name('orders.search-status');
        Route::get('/orders-by-type/{type}', 'Admin\OrderController@ordersByType')->name('orders-by-type.index');
        Route::any('/search-orders', 'Admin\OrderController@search')->name('orders.search');
        Route::get('accept-orders', 'Admin\OrderController@acceptOrders')->name('admin-accept-orders');

app/Models/Period.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Period extends Model
{
    use Notifiable;


    protected $table = 'periods';

    protected $fillable = [
        'active',
        'name_ar','name_en'
    ];

    protected $hidden = [
        'active', 'deleted_at','created_at', 'updated_at'
    ];

//    public function setImageAttribute($value)
//    {
//        if($value) {
//            $img_name = time().uniqid().'.'.$value->getClientOriginalExtension();
//            $value->move(public_path('/uploads/categories/'),$img_name);
//            $this->attributes['image'] = $img_name ;
//        }
//
//    }
//
//    public function getImageAttribute($value)
//    {
//        if($value)
//        {
//            return asset('/uploads/categories/'.$value);
//        }else{
//            return asset('/default.png');
//        }
//    }



}

app/Http/Controllers/Admin/PeriodController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Country;
use Illuminate\Http\Request;
use App\Models\Period;
use DB;
use Route;
use Session;


class PeriodController extends Controller
{
    public function index(){
        $cats = Period::orderBy('id','desc')->get();
        return view('cp.periods.index',[
            'cats'=>$cats
        ]);

    }

    public function store(Request $request)
    {
        $add            = new Period();
        $add->name_ar   = $request->name_ar;
        $add->name_en   = $request->name_en;
        $add->save();
        return back()->with('success','Period added successfully');
    }



    public function editPeriod(Request $request){

        Period::where('id', $request->model_id)
            ->update([
                'name_ar'      => $request->name_ar,
                'name_en'      => $request->name_en,
            ]);
        return back()->with('success','Period updated successfully');
    }
    
    public function editPeriodStatus(Request $request,$id)
    {
        $cat=Period::where("id",$id)->first();
        if($cat->active == 1){
            Period::where("id",$id)
                ->update(["active" => 0 ]);
        }else{
            Period::where("id",$id)
                ->update(["active" => 1 ]);
        }
        return back();
    }

}

resources/views/cp/periods/index.blade.php
@extends('cp.index')
@section('content')
    <div class="page-body" dir="rtl">
        <div class="container-fluid">
            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <div class="page-header-right">


                            @include('cp.layouts.messages')

                            <h3>
                                <i data-feather="home"></i>
                                أوقات التوصيل
                            </h3>
                            {{--<ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('home')}}"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item active">الاقسام</li>
                            </ol>--}}
                        </div>
                        <div style="float: left">
                            @if(auth()->user()->hasPermissionTo('اضافة قسم'))
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#subCat"><i class="icon-plus"></i>
                                إضافة وقت توصيل
                            </button>
                            @endif
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 col-lg-12 col-xl-12">
                    <div class="table-responsive">
                        <table class="table" id="myTable">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">م</th>
                                <th scope="col">الإسم بالعربية</th>
                                <th scope="col">الإسم بالإنجليزية</th>
{{--                                <th scope="col"> الصورة</th>--}}
                                <th scope="col">الإختيارات</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($cats as $c)
                                <tr id="main_cat_{{$c->id}}" onclick="myFunction({{$c->id}})" class="{{$c->active == 0 ? 'table-danger' :''}}">
                                    <td>{{$c->id}}</td>
                                    <td>{{$c->name_ar}}</td>
                                    <td>{{$c->name_en}}</td>
{{--                                    @if($c->image != NULL)--}}
{{--                                        <th><img src="{{$c->image}}"  width="50px" height="50px"></th>--}}
{{--                                    @else--}}
{{--                                        <th> - </th>--}}
{{--                                    @endif--}}
                                    <td>
                                        @if(auth()->user()->hasPermissionTo('تعديل قسم'))
                                        <button title="تعديل" type="button" class="btn btn-warning" data-toggle="modal" data-target="#edit_{{$c->id}}">
                                            <i class="fa fa-edit"></i>
                                        </button>
                                        @endif
                                        @if(auth()->user()->hasPermissionTo('تفعيل قسم'))
                                        @if($c->active == 1)
                                            <a href="{{route('editPeriodStatus',$c->id)}}" >
                                                <button title="إلغاء تفعيل" class="btn btn-danger">
                                                    <i class="fa fa-minus-circle"></i>
                                                </button>
                                            </a>
                                        @else
                                            <a href="{{route('editPeriodStatus',$c->id)}}"  >
                                                <button title="تفعيل" class="btn btn-success">
                                                    <i class="fa fa-plus-circle"></i>
                                                </button>
                                            </a>
                                        @endif
                                        @endif
                                    </td>

                                    <div class="modal fade" id="edit_{{$c->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">تعديل وقت توصيل</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <form class="form-horizontal needs-validation was-validated" method="post" action="{{route('editPeriod')}}" enctype="multipart/form-data">
                                                    {{csrf_field()}}
                                                    <div class="modal-body">
                                                        <input type="hidden" name="model_id" value="{{$c->id}}">


                                                        <div class="form-group row {{ $errors->has('ar_name') ? ' has-error' : '' }}">
                                                            <label class="col-lg-12 control-label text-lg-right"  for="validationCustom04">الإسم بالعربية</label>
                                                            <div class="col-lg-12">
                                                                <input id="inputName1" name="name_ar" type="text" placeholder="الإسم بالعربية" class="form-control btn-square" for="textinput" value="{{$c->name_ar}}" required oninvalid="this.setCustomValidity('هذا الحقل مطلوب إدخاله')">
                                                                <div class="invalid-feedback">هذا الحقل مطلوب إدخاله .</div>
                                                            </div>
                                                        </div>
                                                        @include('cp.layouts.error', ['input' => 'ar_name'])

                                                        <div class="form-group row {{ $errors->has('en_name') ? ' has-error' : '' }}">
                                                            <label class="col-lg-12 control-label text-lg-right" for="textinput">الإسم بالنجليزية</label>
                                                            <div class="col-lg-12">
                                                                <input name="name_en" type="text" placeholder="الإسم بالنجليزية" class="form-control btn-square" for="textinput" value="{{$c->name_en}}" required oninvalid="this.setCustomValidity('هذا الحقل مطلوب إدخاله')">
                                                                <div class="invalid-feedback">هذا الحقل مطلوب إدخاله .</div>
                                                            </div>
                                                        </div>
                                                        @include('cp.layouts.error', ['input' => 'en_name'])

{{--                                                        <div class="form-group ">--}}
{{--                                                            <label  class="col-lg-12 control-label text-lg-right" for="textinput">الصورة</label>--}}
{{--                                                            <input name="image" type="file" class="form-control btn-square" >--}}
{{--                                                        </div>--}}
{{--                                                        @if($c->image != NULL)--}}
{{--                                                            <div class="form-group ">--}}
{{--                                                                <img src="{{  $c->image }}" width="60px" height="60px">--}}
{{--                                                            </div>--}}
{{--                                                        --}}{{--@else--}}
{{--                                                            <div class="form-group ">--}}
{{--                                                                <span>لا توجد صورة</span>--}}
{{--                                                            </div>--}}
{{--                                                        @endif--}}

                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="reset" class="btn btn-dark" data-dismiss="modal">إغلاق</button>
                                                        <button class="btn btn-primary" type="submit">تعديل</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </tr>
                            @endforeach
                            {{--<tbody id="sub_cats_{{$category->id}}"></tbody>--}}
                            </tbody>
                        </table>
                    </div>{{--{{$cats->links()}}--}}
                </div>
            </div>
        </div>
        <!-- Container-fluid Ends-->
    </div>

    <div class="modal fade" id="subCat" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">إضافة وقت توصيل</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form class="form-horizontal needs-validation was-validated" method="post" action="{{route('periods.store')}}" enctype="multipart/form-data">
                    {{csrf_field()}}
                    <div class="modal-body">

                        <div class="form-group ">
                            <label class="col-lg-12 control-label text-lg-right" for="textinput">الإسم بالعربية</label>
                            <div class="col-lg-12">
                                <input name="name_ar" type="text" placeholder="الإسم بالعربية" class="form-control btn-square" required oninvalid="this.setCustomValidity('هذا الحقل مطلوب إدخاله')">
                                <div class="invalid-feedback">هذا الحقل مطلوب إدخاله .</div>
                            </div>
                        </div>

                        <div class="form-group ">
                            <label class="col-lg-12 control-label text-lg-right" for="textinput">الإسم بالإنجليزية</label>
                            <div class="col-lg-12" >
                                <input name="name_en" type="text" placeholder="الإسم بالإنجليزية" class="form-control btn-square" required oninvalid="this.setCustomValidity('هذا الحقل مطلوب إدخاله')">
                                <div class="invalid-feedback">هذا الحقل مطلوب إدخاله .</div>
                            </div>
                        </div>

{{--                        <div class="form-group " >--}}
{{--                            <label class="col-lg-12 control-label text-lg-right" for="textinput">الصورة</label>--}}
{{--                            <input name="image" type="file" class="form-control btn-square" required oninvalid="this.setCustomValidity('هذا الحقل مطلوب إدخاله')">--}}
{{--                            <div class="invalid-feedback">هذا الحقل مطلوب إدخاله .</div>--}}
{{--                        </div>--}}

                    </div>
                    <div class="modal-footer">
                        <button type="reset" class="btn btn-dark" data-dismiss="modal">إغلاق</button>
                        <button class="btn btn-primary">حفظ</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection