routes/web.php
        Route::get('/admins/delet/{id}', 'Admin\User2Controller@deleteAdmin')->name('deleteAdmin');
//
        Route::get('/finished-driver-trips/{driver_id}', 'Admin\User2Controller@finishedDriverTrips');
        Route::get('/finished-user-trips/{user_id}', 'Admin\User2Controller@finishedUserTrips');

        Route::resource('/offer_points', 'Admin\OfferPointController');
        Route::post('/offer_points/edit', 'Admin\OfferPointController@editOfferPoint')->name('editOfferPoint');
        Route::get('/user_offer_points', 'Admin\OfferPointController@user_offer_points');
        Route::get('/user_offer_points/editStatus/{id}', 'Admin\OfferPointController@editUserOfferPointStatus')
            ->name('editUserOfferPointStatus');
        Route::get('/delegate_offer_points', 'Admin\OfferPointController@delegate_offer_points');
        Route::get('/shop_rates/{type}', 'Admin\ShopRateController@index')->name('rates.index');
        Route::get('/download-rates/{department_id}', 'Admin\ShopRateController@downloadRates')->name('download.rates');

        Route::resource('/shop_rates', 'Admin\ShopRateController', ['except' => ['index']]);
        Route::get('/shop_rates/show/{shop_id}', 'Admin\ShopRateController@showRates')->name('shop_rates.show');

        Route::resource('/countriess', 'Admin\CountryController');
        Route::post('/countriess/edit', 'Admin\CountryController@edit_country')->name('editCountry');
        Route::get('/countriess/editStatus/{id}', 'Admin\CountryController@editCountryStatus')->name('editCountryStatus');

        Route::resource('/cities', 'Admin\CityController');
        Route::post('/cities/edit', 'Admin\CityController@edit_city')->name('editCity');
        Route::get('/cities/editStatus/{id}', 'Admin\CityController@editCityStatus')->name('editCityStatus');


        Route::resource('/nationals', 'Admin\NationalController');
        Route::post('/nationals/edit', 'Admin\NationalController@editNational')->name('editNational');
        Route::get('/national/editStatus/{id}', 'Admin\NationalController@editNationalStatus')->name('editNationalStatus');

        Route::get('/car_types/{type}', 'Admin\CarTypeController@index')->name('car_type.index');

        Route::resource('/car_types', 'Admin\CarTypeController', ['except' => ['index']]);
        Route::post('/car_types/edit', 'Admin\CarTypeController@editCarType')->name('editCarType');
        Route::get('/car_types/editStatus/{id}', 'Admin\CarTypeController@editCarTypeStatus')
            ->name('editCarTypeStatus');

        Route::resource('/rushhours', 'Admin\RushhourController');
        Route::post('/rushhours/edit', 'Admin\RushhourController@edit_rushhour')->name('editRushhour');
        Route::get('/rushhours/delet/{id}', 'Admin\RushhourController@delete_rushhour')->name('deleteRushhour');

        Route::resource('/reasons', 'Admin\ReasonController');
        Route::post('/reasons/edit', 'Admin\ReasonController@edit_reason')->name('editReason');
        Route::get('/reasons/delet/{id}', 'Admin\ReasonController@delete_reason')->name('deleteReason');

        Route::resource('/reasons', 'Admin\ReasonController');
        Route::post('/reasons/edit', 'Admin\ReasonController@edit_reason')->name('editReason');
        Route::get('/reasons/delet/{id}', 'Admin\ReasonController@delete_reason')->name('deleteReason');
//
        Route::resource('/issues', 'Admin\IssueController');
        Route::post('/issues/edit', 'Admin\IssueController@edit_issue')->name('editIssue');
        Route::get('/issues/delet/{id}', 'Admin\IssueController@delete_issue')->name('deleteIssue');
//
        Route::resource('/bank_account', 'Admin\BankAccountController');
        Route::post('/bank_account/edit', 'Admin\BankAccountController@edit_bank_account')->name('editBankAccount');
        Route::get('/bank_account/delet/{id}', 'Admin\BankAccountController@delete_bank_account')->name('deleteBankAccount');
//
        Route::resource('/losts', 'Admin\LostController');
        Route::get('/losts-text', 'Admin\LostController@lostText')->name('losts.text');

        Route::post('/losts/edit', 'Admin\LostController@edit_lost')->name('editLost');
        Route::get('/losts/delet/{id}', 'Admin\LostController@delete_lost')->name('deleteLost');
//
        Route::resource('/bank_transfers', 'Admin\BankingTransferController');
        Route::get('/bank_transfers_admin', 'Admin\BankingTransferController@from_admin')->name('bank_transfers.from_admin');
//
        Route::get('/promocodes/{department_id}', 'Admin\PromocodeController@index')->name('promocodes.index');

        Route::resource('/promocodes', 'Admin\PromocodeController', ['except' => ['index']]);
        Route::get('/promocodes/delet/{id}', 'Admin\PromocodeController@delete_promo')->name('deletePromo');

        Route::resource('/carlevelss', 'Admin\LevelController');
        Route::post('/carlevelss/edit', 'Admin\LevelController@edit_carlevels')->name('editCarlevel');
        Route::get('/carlevelss/editStatus/{id}', 'Admin\LevelController@editCarlevelStatus')
            ->name('editCarlevelStatus');

        Route::resource('/carprices', 'Admin\CarPriceController');
        Route::post('/carprices/edit', 'Admin\CarPriceController@edit_carprices')->name('editCarprice');

        Route::resource('/govs', 'Admin\GovController');
        Route::post('/govs/edit', 'Admin\GovController@edit_gov')->name('editGov');

        Route::resource('/cities', 'Admin\CityController');
        Route::post('/cities/edit', 'Admin\CityController@edit_city')->name('editCity');

        Route::resource('/cats', 'Admin\CategoryController');
        Route::post('/cats/edit', 'Admin\CategoryController@edit_cat')->name('editCat');
        Route::get('/cats/editStatus/{id}', 'Admin\CategoryController@editCatStatus')->name('editCatStatus');

        Route::resource('/periods', 'Admin\PeriodController');
        Route::post('/periods/edit', 'Admin\PeriodController@editPeriod')->name('editPeriod');
        Route::get('/periods/editStatus/{id}', 'Admin\PeriodController@editPeriodStatus')->name('editPeriodStatus');


        Route::resource('/trips', 'Admin\TripController');
        Route::get('/finished-trips', 'Admin\TripController@finishedTrips');
        Route::get('/unfinished-trips', 'Admin\TripController@unfinishedTrips');
        Route::get('/cancelled-trips', 'Admin\TripController@cancelledTrips');
        Route::post('/trips', 'Admin\TripController@checkPaymentSrtatus')->name('checkPaymentSrtatus');
//Route::get('/offs/editStatus/{id}', 'Admin\OfferController@editOfferStatus')->name('editOfferStatus');

        Route::resource('/notifications', 'Admin\NotificationController');
        Route::get('/notifications/delet/{id}', 'Admin\NotificationController@delete_not');

        Route::resource('/reviews', 'Admin\ReviewController');
        Route::get('/reviews/delet/{id}', 'Admin\ReviewController@delete_review');

        Route::resource('/terms', 'Admin\TermController');
        Route::post('/terms/edit', 'Admin\TermController@edit_terms')->name('editTerm');
        Route::get('/complains_suggestions/{type}', 'Admin\ComplainSuggestController@index')->name('complains_suggestions.index');
        Route::get('/finished-complains/{type}', 'Admin\ComplainSuggestController@finished')->name('complains_suggestions.finished.index');
        Route::get('/close-complain/{complain_id}', 'Admin\ComplainSuggestController@closeComplain')->name('complain.close');

        Route::resource('/complains_suggestions', 'Admin\ComplainSuggestController', ['except' => ['index']]);
        Route::get('/download-complains/{status}', 'Admin\ComplainSuggestController@downloadComplains')->name('complains.download');

        Route::get('/contact_us/{type}', 'Admin\ContactusController@index')->name('contact_us.index');
        Route::get('/closed-contact_us/{type}', 'Admin\ContactusController@closedContacts')->name('contact_us.closed.index');
        Route::get('/close/{contact_id}', 'Admin\ContactusController@close')->name('contact-us.close');
        Route::resource('/contact_us', 'Admin\ContactusController', ['except' => ['index']]);

        Route::resource('/abouts', 'Admin\AboutController');
        Route::post('/abouts/edit', 'Admin\AboutController@edit_abouts')->name('editAbout');
        Route::get('/settings/{department_id}', 'Admin\SettingController@index')->name('settings.index');

        Route::resource('/settings', 'Admin\SettingController', ['except' => ['index']]);
        Route::post('/settings/edit', 'Admin\SettingController@edit_settings')->name('edit_settings');
        Route::get('/app_explanations/{type}', 'Admin\AppExplanationController@index')->name('app_explanations.index');

        Route::resource('/app_explanations', 'Admin\AppExplanationController', ['except' => ['index']]);
        Route::post('/app_explanations/edit', 'Admin\AppExplanationController@edit_explains')->name('editExplain');
        Route::post('/app_explanations/delet', 'Admin\AppExplanationController@deleteAppExplanations')->name('deleteAppExplanations');

        Route::get('/app_privacies', 'Admin\AppPrivacyController@index');
        Route::post('/app_privacies', 'Admin\AppPrivacyController@createPrivacy')->name('createPrivacy');
        Route::get('/app_privacies/{id}', 'Admin\AppPrivacyController@editView')->name('editPrivacyView');
        Route::post('/app_privacies/edit', 'Admin\AppPrivacyController@edit_explains')->name('editPrivacy');
        Route::post('/app_privacies/delet', 'Admin\AppPrivacyController@deleteAppExplanations')->name('deletePrivacy');


        Route::resource('/categories', 'Admin\CategoryController');
        Route::post('/categories/mainCat', 'Admin\CategoryController@storeMainCat')->name('storeMainCat');
        Route::post('/categories/delet', 'Admin\CategoryController@delete_cat')->name('deleteCat');
        Route::get('/shops/branches/{shop_id}', 'Admin\ShopController@branches')->name('shop.branches');

app/Models/User.php
<?php

namespace App\Models;
use App\Models\Payment;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
//use Laravel\Passport\HasApiTokens;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Str;

class User extends Authenticatable
{
    use  Notifiable;
    //use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'lang',
        'wallet',
        'user_code','name', 'email', 'password','phone','jwt','token','active',
        'lat','lng','image','suspend','verified','wallet_flag','points','promo_code',
        'country_id','gender','user_country_id','rate','no_of_trips','cc_token'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token','email_verified_at','created_at','updated_at','deleted_at',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $appends = ['currency'];
    public function getCurrencyAttribute()
    {
        $lang = request()->header('lang');
        if(!$lang)
            $lang = 'ar';
        if($lang == 'ar')
            return "ريال";
        else
            return "Riyal";
        //
        if(isset($this->attributes['country_id'])){
            return (string)Country::whereId($this->attributes['country_id'])->first()->currency;
        }
        //$country_id = $this->attributes['country_id'];
        if(!isset($this->attributes['country_id'])){
            $lang = request()->header('lang');
            if(!$lang)
                $lang = 'ar';
            if($lang == 'ar')
                return "ريال";
            else
                return "Riyal";
        }
//            $country_id=2;
//
    }

    public function setImageAttribute($value)
    {
        $img_name = time().uniqid().'.'.$value->getClientOriginalExtension();
        $value->move(public_path('/uploads/users/'),$img_name);
        $this->attributes['image'] = $img_name ;
    }

    public function getImageAttribute($value)
    {
        if($value)
        {
            return asset('/uploads/users/'.$value);
        }else{
            return asset('/default.png');
        }
    }

    public function setUserCodeAttribute()
    {
        $this->attributes['user_code'] = rand(100,999) .' - '. Str::random(3) ;
    }

    public function setPasswordAttribute()
    {
        $this->attributes['password'] = Hash::make(request()->password) ;
    }

    public function getIsCaptinAttribute($value)
    {
        return (int)$value;
    }

    public function getRateAttribute($value)
    {
        if($value == null)
            return 0;
        return (int)$value;
    }

    public function getUserCountryIdAttribute($value)
    {
        if($value == null)
            return 0;
        return (int)$value;
    }
    public function getPromoCodeAttribute($value)
    {
        if($value == null)
            return "0";
        return (int)$value;
    }

    public function getGenderAttribute($value)
    {
        if($value == null)
            return 0;
        return (int)$value;
    }

    public function user_replaced_points(){
        return $this->hasMany(UserReplacedPoint::class,"user_id");
    }

    public function user_wallet_recharges(){
        return $this->hasMany(WalletRecharge::class,"user_id",'id');
    }

    public function country(){
        return $this->belongsTo(Country::class,"country_id");
    }


    public function transactions()
    {
        return $this->morphMany(Payment::class,'attribute')->where('status',1);
    }



}

app/Http/Controllers/Admin/IssueController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\CancellingReason;
use App\Models\Country;
use App\Models\Gov;
use App\Models\Issue;
use Illuminate\Http\Request;
use App\Models\Rushhour;
use DB;
use Route;
use Session;


class IssueController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(){
        $results = Issue::orderBy('id','desc')
            ->get();
        return view('cp.issues.index',[
            'results'=>$results,
        ]);

    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'ar_issue' => 'required',
            'en_issue' => 'required',
            'is_captin' => 'required',
        ]);
        $add                = new Issue();
        $add->ar_issue        = $request->ar_issue;
        $add->en_issue        = $request->en_issue;
        $add->is_captin     = $request->is_captin;
        $add->save();
        session()->flash('insert_message','تمت العملية بنجاح');
        return back()->with('success','Record added successfully');
    }



    public function edit_issue(Request $request){
        $this->validate($request,[
            'ar_issue' => 'required',
            'en_issue' => 'required',
            'is_captin' => 'required',
        ]);
        $c=Issue::where('id', $request->issue_id)->first();
        $c->update($request->all());

        session()->flash('insert_message','تمت العملية بنجاح');
        return back()->with('success','Record updated successfully');
    }

    public function delete_issue(Request $request,$id){

        Issue::destroy($id);

        session()->flash('insert_message','تمت العملية بنجاح');
        return back()->with('success','Record deleted successfully');
    }

}

app/Http/Controllers/Shop/IssueController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\CancellingReason;
use App\Models\Country;
use App\Models\Gov;
use App\Models\Issue;
use Illuminate\Http\Request;
use App\Models\Rushhour;
use DB;
use Route;
use Session;


class IssueController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(){
        $results = Issue::orderBy('id','desc')
            ->get();
        return view('cp.issues.index',[
            'results'=>$results,
        ]);

    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'ar_issue' => 'required',
            'en_issue' => 'required',
            'is_captin' => 'required',
        ]);
        $add                = new Issue();
        $add->ar_issue        = $request->ar_issue;
        $add->en_issue        = $request->en_issue;
        $add->is_captin     = $request->is_captin;
        $add->save();
        session()->flash('insert_message','تمت العملية بنجاح');
        return back()->with('success','Record added successfully');
    }



    public function edit_issue(Request $request){
        $this->validate($request,[
            'ar_issue' => 'required',
            'en_issue' => 'required',
            'is_captin' => 'required',
        ]);
        $c=Issue::where('id', $request->issue_id)->first();
        $c->update($request->all());

        session()->flash('insert_message','تمت العملية بنجاح');
        return back()->with('success','Record updated successfully');
    }

    public function delete_issue(Request $request,$id){

        Issue::destroy($id);

        session()->flash('insert_message','تمت العملية بنجاح');
        return back()->with('success','Record deleted successfully');
    }

}

resources/views/cp/issues/index.blade.php
@extends('cp.index')
@section('content')
    <div class="page-body" dir="rtl">
        <div class="container-fluid">
            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <div class="page-header-right">


                            @include('cp.layouts.messages')


                            <h3>
                                <i data-feather="home"></i>
                                المشكلات
                            </h3>
                            {{--<ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('home')}}"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item active">الدول</li>
                            </ol>--}}
                        </div>
                        <div style="float: left">
                            @if(auth()->user()->hasPermissionTo('اضافة مشكلة'))
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#subCat"><i class="icon-plus"></i>
                                إضافة النص
                            </button>
                            @endif
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 col-lg-12 col-xl-12">
                    <div class="table-responsive">
                        <table class="table" id="myTable">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">م</th>

                                <th scope="col"> النص بالعربية </th>
                                <th scope="col"> النص بالإنجليزية </th>
                                <th scope="col">التحديد</th>

                                <th scope="col">الإختيارات</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($results as $c)
                                <tr id="main_cat_{{$c->id}}" onclick="myFunction({{$c->id}})">
                                    <td>{{$c->id}}</td>

                                    <td>{{$c->ar_issue}}</td>
                                    <td>{{$c->en_issue}}</td>
                                    <td>{{$c->is_captin == 1 ? "خاص بالسائق" : "خاص بالمستخدم"}}</td>

                                    <td>
                                        @if(auth()->user()->hasPermissionTo('تعديل مشكلة'))
                                        <button title="تعديل" type="button" class="btn btn-warning" data-toggle="modal" data-target="#edit_{{$c->id}}">
                                            <i class="fa fa-edit"></i>
                                        </button>
                                        @endif

                                        @if(auth()->user()->hasPermissionTo('حذف مشكلة'))
{{--                                        <a href="{{route('deleteIssue',$c->id)}}" data-original-title="" title="">--}}
                                            <button title="" class="btn btn-danger" data-original-title="حذف" data-toggle="modal" data-target="#delete_{{$c->id}}">
                                                <i class="fa fa-trash"></i>
                                            </button>
{{--                                        </a>--}}
                                        @endif
                                    </td>

                                    <div class="modal fade" id="edit_{{$c->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">تعديل النص</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <form class="form-horizontal" method="post" action="{{route('editIssue')}}" enctype="multipart/form-data">
                                                    {{csrf_field()}}
                                                    <div class="modal-body">
                                                        <input type="hidden" name="issue_id" value="{{$c->id}}">


                                                        <div class="form-group row ">
                                                            <label class="col-lg-12 control-label text-lg-right" for="textinput">النص بالعربية</label>
                                                            <div class="col-lg-12">
                                                                <input name="ar_issue" class="form-control" type="text" value="{{$c->ar_issue}}" >
                                                            </div>
                                                        </div>
                                                        <div class="form-group row ">
                                                            <label class="col-lg-12 control-label text-lg-right" for="textinput">النص بالإنجليزية</label>
                                                            <div class="col-lg-12">
                                                                <input name="en_issue" class="form-control" type="text" value="{{$c->en_issue}}" >
                                                            </div>
                                                        </div>
                                                        <div class="form-group row ">
                                                            <label class="col-lg-12 control-label text-lg-right" for="textinput"> تحديد</label>
                                                            <div class="col-lg-12">
                                                                <select name="is_captin" class="form-control digits" id="exampleFormControlSelect9">
                                                                    <option value="0" {{$c->is_captin == 0 ? "selected" : ""}}>خاص بالمستخدم</option>
                                                                    <option value="1" {{$c->is_captin == 1 ? "selected" : ""}}>خاص بالسائق</option>
                                                                </select>
                                                            </div>
                                                        </div>


                                                    </div>






                                                    <div class="modal-footer">
                                                        <button type="reset" class="btn btn-dark" data-dismiss="modal">إغلاق</button>
                                                        <button class="btn btn-primary" type="submit">تعديل</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="modal animated fadeIn" id="delete_{{$c->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header btn-danger">
                                                    <h5 class="modal-title" id="exampleModalLabel">هل انت متأكد ؟</h5>
                                                    {{--                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">--}}
                                                    {{--                                                <span aria-hidden="true">&times;</span>--}}
                                                    {{--                                            </button>--}}
                                                </div>
                                                <form method="get" action="{{route('deleteIssue',$c->id)}}" class="buttons">
                                                    {{csrf_field()}}
                                                    <div class="modal-body">
                                                        <h6>
                                                            انت علي وشك حذف الحقل

                                                        </h6>
                                                    </div>
                                                    <div class="modal-footer">
                                                        {{--                                                        <input type="hidden" name="model_id" value="{{$result->id}}">--}}
                                                        <button class="btn btn-dark" type="button" data-dismiss="modal">إغلاق</button>
                                                        <button type="submit" class="btn btn-danger">تأكيد</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>

                                </tr>
                            @endforeach
                            {{--<tbody id="sub_cats_{{$category->id}}"></tbody>--}}
                            </tbody>
                        </table>
                    </div>{{--{{$countries->links()}}--}}
                </div>
            </div>
        </div>
        <!-- Container-fluid Ends-->

    </div>

    <div class="modal fade" id="subCat" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">إضافة نص جديد</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form class="form-horizontal needs-validation was-validated" method="post" action="{{route('issues.store')}}" enctype="multipart/form-data">
                    {{csrf_field()}}
                    <div class="modal-body">



                        <div class="form-group row ">
                            <label class="col-lg-12 control-label text-lg-right" for="textinput">النص بالعربية</label>
                            <div class="col-lg-12">
                                <input name="ar_issue" class="form-control digits" type="text" required>
                                <div class="invalid-feedback">هذا الحقل مطلوب إدخاله .</div>
                            </div>
                        </div>
                        <div class="form-group row ">
                            <label class="col-lg-12 control-label text-lg-right" for="textinput">النص بالإنجليزية</label>
                            <div class="col-lg-12">
                                <input name="en_issue" class="form-control digits" type="text" required>
                                <div class="invalid-feedback">هذا الحقل مطلوب إدخاله .</div>
                            </div>
                        </div>
                        <div class="form-group row ">
                            <label class="col-lg-12 control-label text-lg-right" for="textinput"> تحديد</label>
                            <div class="col-lg-12">
                                <select name="is_captin" class="form-control digits" id="exampleFormControlSelect9" required>
                                    <option value="0" >خاص بالمستخدم</option>
                                    <option value="1" >خاص بالسائق</option>
                                </select>
                                <div class="invalid-feedback">هذا الحقل مطلوب إدخاله .</div>
                            </div>
                        </div>

                    </div>




                    <div class="modal-footer">
                        <button type="reset" class="btn btn-dark" data-dismiss="modal">إغلاق</button>
                        <button class="btn btn-primary">حفظ</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection