routes/web.php
        Route::resource('/sub_departments', 'Admin\SubDepartmentController');
        Route::get('/get_sub_departments/{department_id}', 'Admin\SubDepartmentController@getSubDepartments');
        Route::post('/sub_departments/edit', 'Admin\SubDepartmentController@editSubDepartment')
            ->name('editSubDepartment');
        Route::get('/sub_departments/editStatus/{id}', 'Admin\SubDepartmentController@editSubDepartmentStatus')
            ->name('editSubDepartmentStatus');

        //chat between admin and users
        Route::get('chat', 'Admin\ChatController@index');
        Route::get('reply/{id}', 'Admin\ChatController@reply')->name('admin.reply');
        Route::post('send', 'Admin\ChatController@create_message')->name('admin.send');

        Route::get('/sliders', 'Admin\SliderController@index')->name('sliders');
        Route::post('/sliders', 'Admin\SliderController@store')->name('sliders-store');
        Route::post('/sliders/edit', 'Admin\SliderController@editSlider')->name('editSlider');
        Route::get('/sliders/delet/{id}', 'Admin\SliderController@deleteSlider')->name('deleteSlider');

        Route::resource('/clients', 'Admin\User2Controller');
        Route::get('/clients/editStatus/{id}', 'Admin\User2Controller@editClientStatus')->name('editClientStatus');
        Route::get('/clients/complains/{user_id}', 'Admin\User2Controller@complains')->name('users.complains');

        Route::get('/clients/orders/{user_id}/{department_id}', 'Admin\User2Controller@orders')->name('users.orders');
        Route::post('/clients/orders-search', 'Admin\User2Controller@searchOrders')->name('users.orders.search');
        Route::get('/clients/trips/{user_id}', 'Admin\User2Controller@trips')->name('users.trips');
        Route::get('/clients/wallets/{user_id}', 'Admin\User2Controller@wallets')->name('users.wallets');
        Route::get('/delegates', 'Admin\User2Controller@index3');
        Route::post('/edit-documents', 'Admin\User2Controller@editDocuments')->name('edit-documents');
        Route::get('/download-delegates/{accept}/{type}', 'Admin\User2Controller@downloadDelegates')->name('delegates.download');
        Route::get('/delegates-with-area', 'Admin\User2Controller@indexDelegatesWithAreas')->name('delegates.with-areas');
        Route::post('/delegates-with-area', 'Admin\User2Controller@delegatesAreasSearch')->name('delegates.areas.search');
        Route::get('/delegates/waiting', 'Admin\User2Controller@waitingDelegates');
        Route::get('/delegates-heavey', 'Admin\User2Controller@index3Heavey');
        Route::get('/delegates-shops/{delegate_id}', 'Admin\User2Controller@delegateShops')->name('delegate.shops');
        Route::get('/delegates-heavy-with-area', 'Admin\User2Controller@indexHeavyDelegatesWithAreas')->name('heavy-delegates.with-areas');
        Route::post('/delegates-heavy-with-area', 'Admin\User2Controller@heavyDelegatesAreasSearch')->name('heavy-delegates.areas.search');

        Route::get('/delegates-heavey/waiting', 'Admin\User2Controller@waitingDelegatesHeavey');
        Route::get('/delegate-orders/{delegate_id}', 'Admin\User2Controller@delegateOrders')->name('delegateOrders');
        Route::get('/delegates/editStatus/{id}', 'Admin\User2Controller@editDelegateStatus')->name('editDelegateStatus');
        Route::get('/delegates/editReasonStatus/{id}', 'Admin\User2Controller@editReasonStatus')
            ->name('editReasonStatus');
        Route::get('/drivers/editDriverReasonStatus/{id}', 'Admin\User2Controller@editDriverReasonStatus')
            ->name('editDriverReasonStatus');

        Route::get('/drivers', 'Admin\User2Controller@index2');
        Route::get('/drivers-trips-download/{driver_id}', 'Admin\User2Controller@downloadTrips')->name('download.trips');
        Route::get('/drivers-download\{active}', 'Admin\User2Controller@downloadDrivers')->name('drivers.download');
        Route::get('/drivers/waiting', 'Admin\User2Controller@waitingDrivers');
        Route::get('/all-drivers', 'Admin\User2Controller@allDrivers')->name('all-drivers');
        Route::get('/drivers-with-area', 'Admin\User2Controller@driversByArea')->name('drivers-by-area');
        Route::post('/drivers-with-area', 'Admin\User2Controller@driversByAreaSearch')->name('drivers-by-area-search');
        Route::get('/driver-trips/{driver_id}', 'Admin\User2Controller@driverTrips')->name('driverTrips');
        Route::post('/driver-trips/search', 'Admin\User2Controller@tripsSearch')->name('trips.search');
        Route::get('/user-trips/{user_id}', 'Admin\User2Controller@userTrips')->name('userTrips');
        Route::get('/drivers/accept/{id}', 'Admin\User2Controller@accept_driver')->name('acceptDriver');
        Route::get('/delegates/accept/{id}', 'Admin\User2Controller@accept_delegate')->name('acceptDelegate');
        Route::post('/drivers/editCarLevel', 'Admin\User2Controller@editCarLevel')->name('editCarLevel');

        Route::post('/drivers/editCarLevelFlag', 'Admin\User2Controller@editCarLevelFlag')
            ->name('editCarLevelFlag');
        Route::get('/drivers/editStatus/{id}', 'Admin\User2Controller@editDriverStatus')->name('editDriverStatus');

        Route::get('/drivers/calculations/{driver_id}', 'Admin\User2Controller@calculationsDrivers');
        Route::get('/delegates/calculations/{delegate_id}', 'Admin\User2Controller@calculationsDelegates');
        Route::post('/delegates/search-orders', 'Admin\User2Controller@searchDelegateOrders')->name('delegate.orders.search');
        Route::get('/delegates-heavey/calculations/{delegate_id}', 'Admin\User2Controller@calculationsDelegatesHeavey');


        Route::get('/admins', 'Admin\User2Controller@indexAdmin');
        Route::get('/download-admin', 'Admin\AdminController@downloadAdmins')->name('admins.download');
        Route::get('/admins/create', 'Admin\User2Controller@createAdminForm')->name('admin.create');
        Route::get('/admins-by-area', 'Admin\User2Controller@adminsByArea')->name('admin.admins-by-area');
        Route::post('/admins-by-area', 'Admin\User2Controller@adminsByAreaSearch')->name('admin.admins-by-area-search');
        Route::post('/createAdmin', 'Admin\User2Controller@createAdmin')->name('createAdmin');
        Route::post('/editAdmin', 'Admin\User2Controller@editAdmin')->name('editAdmin');
        Route::get('/admins/editStatus/{id}', 'Admin\User2Controller@editAdminStatus')->name('editAdminStatus');
        Route::get('/admins/delet/{id}', 'Admin\User2Controller@deleteAdmin')->name('deleteAdmin');
//
        Route::get('/finished-driver-trips/{driver_id}', 'Admin\User2Controller@finishedDriverTrips');
        Route::get('/finished-user-trips/{user_id}', 'Admin\User2Controller@finishedUserTrips');

        Route::resource('/offer_points', 'Admin\OfferPointController');
        Route::post('/offer_points/edit', 'Admin\OfferPointController@editOfferPoint')->name('editOfferPoint');
        Route::get('/user_offer_points', 'Admin\OfferPointController@user_offer_points');
        Route::get('/user_offer_points/editStatus/{id}', 'Admin\OfferPointController@editUserOfferPointStatus')
            ->name('editUserOfferPointStatus');
        Route::get('/delegate_offer_points', 'Admin\OfferPointController@delegate_offer_points');
        Route::get('/shop_rates/{type}', 'Admin\ShopRateController@index')->name('rates.index');
        Route::get('/download-rates/{department_id}', 'Admin\ShopRateController@downloadRates')->name('download.rates');

        Route::resource('/shop_rates', 'Admin\ShopRateController', ['except' => ['index']]);
        Route::get('/shop_rates/show/{shop_id}', 'Admin\ShopRateController@showRates')->name('shop_rates.show');

        Route::resource('/countriess', 'Admin\CountryController');
        Route::post('/countriess/edit', 'Admin\CountryController@edit_country')->name('editCountry');
        Route::get('/countriess/editStatus/{id}', 'Admin\CountryController@editCountryStatus')->name('editCountryStatus');

        Route::resource('/cities', 'Admin\CityController');
        Route::post('/cities/edit', 'Admin\CityController@edit_city')->name('editCity');
        Route::get('/cities/editStatus/{id}', 'Admin\CityController@editCityStatus')->name('editCityStatus');


        Route::resource('/nationals', 'Admin\NationalController');
        Route::post('/nationals/edit', 'Admin\NationalController@editNational')->name('editNational');
        Route::get('/national/editStatus/{id}', 'Admin\NationalController@editNationalStatus')->name('editNationalStatus');

        Route::get('/car_types/{type}', 'Admin\CarTypeController@index')->name('car_type.index');

        Route::resource('/car_types', 'Admin\CarTypeController', ['except' => ['index']]);
        Route::post('/car_types/edit', 'Admin\CarTypeController@editCarType')->name('editCarType');
        Route::get('/car_types/editStatus/{id}', 'Admin\CarTypeController@editCarTypeStatus')
            ->name('editCarTypeStatus');

        Route::resource('/rushhours', 'Admin\RushhourController');
        Route::post('/rushhours/edit', 'Admin\RushhourController@edit_rushhour')->name('editRushhour');
        Route::get('/rushhours/delet/{id}', 'Admin\RushhourController@delete_rushhour')->name('deleteRushhour');

        Route::resource('/reasons', 'Admin\ReasonController');
        Route::post('/reasons/edit', 'Admin\ReasonController@edit_reason')->name('editReason');
        Route::get('/reasons/delet/{id}', 'Admin\ReasonController@delete_reason')->name('deleteReason');

        Route::resource('/reasons', 'Admin\ReasonController');
        Route::post('/reasons/edit', 'Admin\ReasonController@edit_reason')->name('editReason');
        Route::get('/reasons/delet/{id}', 'Admin\ReasonController@delete_reason')->name('deleteReason');
//
        Route::resource('/issues', 'Admin\IssueController');
        Route::post('/issues/edit', 'Admin\IssueController@edit_issue')->name('editIssue');

app/Models/User.php
<?php

namespace App\Models;
use App\Models\Payment;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
//use Laravel\Passport\HasApiTokens;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Str;

class User extends Authenticatable
{
    use  Notifiable;
    //use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'lang',
        'wallet',
        'user_code','name', 'email', 'password','phone','jwt','token','active',
        'lat','lng','image','suspend','verified','wallet_flag','points','promo_code',
        'country_id','gender','user_country_id','rate','no_of_trips','cc_token'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token','email_verified_at','created_at','updated_at','deleted_at',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected $appends = ['currency'];
    public function getCurrencyAttribute()
    {
        $lang = request()->header('lang');
        if(!$lang)
            $lang = 'ar';
        if($lang == 'ar')
            return "ريال";
        else
            return "Riyal";
        //
        if(isset($this->attributes['country_id'])){
            return (string)Country::whereId($this->attributes['country_id'])->first()->currency;
        }
        //$country_id = $this->attributes['country_id'];
        if(!isset($this->attributes['country_id'])){
            $lang = request()->header('lang');
            if(!$lang)
                $lang = 'ar';
            if($lang == 'ar')
                return "ريال";
            else
                return "Riyal";
        }
//            $country_id=2;
//
    }

    public function setImageAttribute($value)
    {
        $img_name = time().uniqid().'.'.$value->getClientOriginalExtension();
        $value->move(public_path('/uploads/users/'),$img_name);
        $this->attributes['image'] = $img_name ;
    }

    public function getImageAttribute($value)
    {
        if($value)
        {
            return asset('/uploads/users/'.$value);
        }else{
            return asset('/default.png');
        }
    }

    public function setUserCodeAttribute()
    {
        $this->attributes['user_code'] = rand(100,999) .' - '. Str::random(3) ;
    }

    public function setPasswordAttribute()
    {
        $this->attributes['password'] = Hash::make(request()->password) ;
    }

    public function getIsCaptinAttribute($value)
    {
        return (int)$value;
    }

    public function getRateAttribute($value)
    {
        if($value == null)
            return 0;
        return (int)$value;
    }

    public function getUserCountryIdAttribute($value)
    {
        if($value == null)
            return 0;
        return (int)$value;
    }
    public function getPromoCodeAttribute($value)
    {
        if($value == null)
            return "0";
        return (int)$value;
    }

    public function getGenderAttribute($value)
    {
        if($value == null)
            return 0;
        return (int)$value;
    }

    public function user_replaced_points(){
        return $this->hasMany(UserReplacedPoint::class,"user_id");
    }

    public function user_wallet_recharges(){
        return $this->hasMany(WalletRecharge::class,"user_id",'id');
    }

    public function country(){
        return $this->belongsTo(Country::class,"country_id");
    }


    public function transactions()
    {
        return $this->morphMany(Payment::class,'attribute')->where('status',1);
    }



}

app/Http/Controllers/Admin/ReasonController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\CancellingReason;
use App\Models\Country;
use App\Models\Gov;
use Illuminate\Http\Request;
use App\Models\Rushhour;
use DB;
use Route;
use Session;


class ReasonController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(){
        $results = CancellingReason::orderBy('id','desc')
            ->get();
        return view('cp.reasons.index',[
            'results'=>$results,
        ]);

    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'ar_reason' => 'required',
            'en_reason' => 'required',
            'is_captin' => 'required',
        ]);
        $add                = new CancellingReason();
        $add->ar_reason        = $request->ar_reason;
        $add->en_reason        = $request->en_reason;
        $add->is_captin     = $request->is_captin;
        $add->save();
        session()->flash('insert_message','تمت العملية بنجاح');
        return back()->with('success','Record added successfully');
    }



    public function edit_reason(Request $request){
        $this->validate($request,[
            'ar_reason' => 'required',
            'en_reason' => 'required',
            'is_captin' => 'required',
        ]);
        $c=CancellingReason::where('id', $request->reason_id)->first();
        $c->update($request->all());

        session()->flash('insert_message','تمت العملية بنجاح');
        return back()->with('success','Record updated successfully');
    }

    public function delete_reason(Request $request,$id){

        CancellingReason::destroy($id);

        session()->flash('insert_message','تمت العملية بنجاح');
        return back()->with('success','Record deleted successfully');
    }

}

app/Http/Controllers/Shop/ReasonController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\CancellingReason;
use App\Models\Country;
use App\Models\Gov;
use Illuminate\Http\Request;
use App\Models\Rushhour;
use DB;
use Route;
use Session;


class ReasonController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(){
        $results = CancellingReason::orderBy('id','desc')
            ->get();
        return view('cp.reasons.index',[
            'results'=>$results,
        ]);

    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'ar_reason' => 'required',
            'en_reason' => 'required',
            'is_captin' => 'required',
        ]);
        $add                = new CancellingReason();
        $add->ar_reason        = $request->ar_reason;
        $add->en_reason        = $request->en_reason;
        $add->is_captin     = $request->is_captin;
        $add->save();
        session()->flash('insert_message','تمت العملية بنجاح');
        return back()->with('success','Record added successfully');
    }



    public function edit_reason(Request $request){
        $this->validate($request,[
            'ar_reason' => 'required',
            'en_reason' => 'required',
            'is_captin' => 'required',
        ]);
        $c=CancellingReason::where('id', $request->reason_id)->first();
        $c->update($request->all());

        session()->flash('insert_message','تمت العملية بنجاح');
        return back()->with('success','Record updated successfully');
    }

    public function delete_reason(Request $request,$id){

        CancellingReason::destroy($id);

        session()->flash('insert_message','تمت العملية بنجاح');
        return back()->with('success','Record deleted successfully');
    }

}

resources/views/cp_shop/reasons/index.blade.php
@extends('cp.index')
@section('content')
    <div class="page-body" dir="rtl">
        <div class="container-fluid">
            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <div class="page-header-right">


                            @include('cp.layouts.messages')


                            <h3>
                                <i data-feather="home"></i>
                                اسباب إلغاء الرحلة
                            </h3>
                            {{--<ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('home')}}"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item active">الدول</li>
                            </ol>--}}
                        </div>
                        <div style="float: left">
                            {{--@if(admin()->hasPermissionTo('Add country'))--}}
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#subCat"><i class="icon-plus"></i>
                                إضافة سبب
                            </button>
                            {{--@endif--}}
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12 col-lg-12 col-xl-12">
                    <div class="table-responsive">
                        <table class="table" id="myTable">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">#</th>

                                <th scope="col"> السبب بالعربية </th>
                                <th scope="col"> السبب بالإنجليزية </th>
                                <th scope="col">التحديد</th>

                                <th scope="col">الإختيارات</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($results as $c)
                                <tr id="main_cat_{{$c->id}}" onclick="myFunction({{$c->id}})">
                                    <td>{{$c->id}}</td>

                                    <td>{{$c->ar_reason}}</td>
                                    <td>{{$c->en_reason}}</td>
                                    <td>{{$c->is_captin == 1 ? "خاص بالسائق" : "خاص بالمستخدم"}}</td>

                                    <td>
                                        {{--@if(admin()->hasPermissionTo('Edit City'))--}}
                                        <button title="تعديل" type="button" class="btn btn-warning" data-toggle="modal" data-target="#edit_{{$c->id}}">
                                            <i class="fa fa-edit"></i>
                                        </button>
                                        {{--@endif--}}

                                        <a href="{{route('deleteReason',$c->id)}}" data-original-title="" title="">
                                            <button title="" class="btn btn-danger" data-original-title="حذف">
                                                <i class="fa fa-minus-circle"></i>
                                            </button>
                                        </a>
                                    </td>

                                    <div class="modal fade" id="edit_{{$c->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">تعديل السبب</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <form class="form-horizontal" method="post" action="{{route('editReason')}}" enctype="multipart/form-data">
                                                    {{csrf_field()}}
                                                    <div class="modal-body">
                                                        <input type="hidden" name="reason_id" value="{{$c->id}}">


                                                        <div class="form-group row ">
                                                            <label class="col-lg-12 control-label text-lg-right" for="textinput">السبب بالعربية</label>
                                                            <div class="col-lg-12">
                                                                <input name="ar_reason" class="form-control" type="text" value="{{$c->ar_reason}}" >
                                                            </div>
                                                        </div>
                                                        <div class="form-group row ">
                                                            <label class="col-lg-12 control-label text-lg-right" for="textinput">السبب بالإنجليزية</label>
                                                            <div class="col-lg-12">
                                                                <input name="en_reason" class="form-control" type="text" value="{{$c->en_reason}}" >
                                                            </div>
                                                        </div>
                                                        <div class="form-group row ">
                                                            <label class="col-lg-12 control-label text-lg-right" for="textinput"> تحديد</label>
                                                            <div class="col-lg-12">
                                                                <select name="is_captin" class="form-control digits" id="exampleFormControlSelect9">
                                                                    <option value="0" {{$c->is_captin == 0 ? "selected" : ""}}>خاص بالمستخدم</option>
                                                                    <option value="1" {{$c->is_captin == 1 ? "selected" : ""}}>خاص بالسائق</option>
                                                                </select>
                                                            </div>
                                                        </div>


                                                    </div>






                                                    <div class="modal-footer">
                                                        <button type="reset" class="btn btn-dark" data-dismiss="modal">إغلاق</button>
                                                        <button class="btn btn-primary" type="submit">تعديل</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </tr>
                            @endforeach
                            {{--<tbody id="sub_cats_{{$category->id}}"></tbody>--}}
                            </tbody>
                        </table>
                    </div>{{--{{$countries->links()}}--}}
                </div>
            </div>
        </div>
        <!-- Container-fluid Ends-->

    </div>

    <div class="modal fade" id="subCat" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">إضافة سبب جديد</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form class="form-horizontal needs-validation was-validated" method="post" action="{{route('reasons.store')}}" enctype="multipart/form-data">
                    {{csrf_field()}}
                    <div class="modal-body">



                        <div class="form-group row ">
                            <label class="col-lg-12 control-label text-lg-right" for="textinput">السبب بالعربية</label>
                            <div class="col-lg-12">
                                <input name="ar_reason" class="form-control digits" type="text" required>
                                <div class="invalid-feedback">هذا الحقل مطلوب إدخاله .</div>
                            </div>
                        </div>
                        <div class="form-group row ">
                            <label class="col-lg-12 control-label text-lg-right" for="textinput">السبب بالإنجليزية</label>
                            <div class="col-lg-12">
                                <input name="en_reason" class="form-control digits" type="text" required>
                                <div class="invalid-feedback">هذا الحقل مطلوب إدخاله .</div>
                            </div>
                        </div>
                        <div class="form-group row ">
                            <label class="col-lg-12 control-label text-lg-right" for="textinput"> تحديد</label>
                            <div class="col-lg-12">
                                <select name="is_captin" class="form-control digits" id="exampleFormControlSelect9" required>
                                    <option value="0" >خاص بالمستخدم</option>
                                    <option value="1" >خاص بالسائق</option>
                                </select>
                                <div class="invalid-feedback">هذا الحقل مطلوب إدخاله .</div>
                            </div>
                        </div>

                    </div>




                    <div class="modal-footer">
                        <button type="reset" class="btn btn-dark" data-dismiss="modal">إغلاق</button>
                        <button class="btn btn-primary">حفظ</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection